name: Save Docker Images and Upload to Release

on:
  push:
    branches: [ "main" ]

jobs:
  save-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: 安裝 Docker
        uses: docker/setup-buildx-action@v3

      - name: 拉取映像
        run: |
          docker pull docker.io/library/redis:7.2
          docker pull docker.io/library/redis:7.2-alpine
          docker pull registry.access.redhat.com/ubi9/ubi-minimal:latest
          docker pull registry.access.redhat.com/ubi9/ubi:latest
          docker pull registry.access.redhat.com/redis/redis-stack-server:latest

      - name: 儲存為 .tar 文件
        run: |
          mkdir -p docker_images
          docker save docker.io/library/redis:7.2 > docker_images/redis-7.2.tar
          docker save docker.io/library/redis:7.2-alpine > docker_images/redis-7.2-alpine.tar
          docker save registry.access.redhat.com/ubi9/ubi-minimal:latest > docker_images/radhat-ubi9-minimal.tar
          docker save registry.access.redhat.com/ubi9/ubi:latest > docker_images/radhat-ubi9.tar
          docker save registry.access.redhat.com/redis/redis-stack-server:latest > docker_images/radhat-redis-stack-server.tar

      - name: 建立或更新 Release 並上傳檔案
        uses: softprops/action-gh-release@v1
        with:
          tag_name: docker-images-v1
          name: "Docker Images Release"
          files: |
            docker_images/redis-7.2.tar
            docker_images/redis-7.2-alpine.tar
            docker_images/radhat-ubi9-minimal.tar
            docker_images/radhat-ubi9.tar
            docker_images/radhat-redis-stack-server.tar
          fail_on_unmatched_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
