name: Save Docker Images and Upload to Release

on:
  push:
    branches: [ "main" ]

jobs:
  save-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: 安裝 podman
        run: |
          sudo apt update
          sudo apt install -y podman gzip

      - name: 拉取映像
        run: |
          podman pull docker.io/redis:7.2
          podman pull registry.access.redhat.com/ubi8/ubi-minimal:latest
          podman pull registry.k8s.io/pause:3.9

      - name: 儲存並壓縮為 .tar.gz
        run: |
          mkdir -p docker_images
          podman save docker.io/redis:7.2 | gzip > docker_images/redis-7.2.tar.gz
          podman save registry.access.redhat.com/ubi8/ubi-minimal:latest | gzip > docker_images/ubi8-minimal.tar.gz
          podman save registry.k8s.io/pause:3.9 | gzip > docker_images/k8s-pause.tar.gz

      - name: 建立或更新 Release 並上傳檔案
        uses: softprops/action-gh-release@v1
        with:
          tag_name: docker-images-v1
          name: "Docker Images Release"
          files: |
            docker_images/redis-7.2.tar.gz
            docker_images/ubi8-minimal.tar.gz
            docker_images/k8s-pause.tar.gz
          fail_on_unmatched_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
